#!usr/bin/perl -w
use strict;
my ($USAGE) = "$0 DNA\n\n";
unless (@ARGV) {
print $USAGE;
exit;
}
my $DNA = $ARGV[0];
my ($Gs) = countG($DNA);
print "\n G has $Gs in the $DNA\n\n";
exit;
sub countG{
 my ($DNA) = @_;
 my $count = 0;
 $count = ($DNA =~ tr/Gs//);
 return $count;
}
